#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"

cage=${1:-cage}
name=$(basename "$cage")

ARCH=${ARCH:-$(dpkg-architecture -q DEB_BUILD_ARCH)}
DIST=${DIST:-$(lsb_release -cs)}

cyan -n "Bootstrapping $name "; echo "$ARCH $DIST"
sleep 3

mirror=
if [[ "$DIST" == "pika" ]]; then
    mirror=https://ppa.pika-os.com keyring=/tmp/pika.gpg
    wget -qU "Debian APT-HTTP/1.3 (1.2.3)" -O- $mirror/key.gpg | gpg --dearmor > $keyring

    suite=(
        --components=nest,cockatiel
        --variant=essential
        --include='~prequired !~E !~npika-baseos' --include=pika-sources
        --keyring=$keyring
    )

elif [[ "$DIST" == "unstable" || "$DIST" == "sid" ]]; then
    suite=(
        --components=main
        --variant=required
        --customize-hook="cat > \$1/etc/apt/sources.list.d/debian-sid.sources <<EOF
Types: deb
URIs: http://deb.debian.org/debian
Suites: $DIST
Components: main contrib non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF"
    )

elif [[ "$DIST" == "stable" ]] || debian-distro-info --all | grep -qx "$DIST"; then
    suite=(
        --components=main
        --variant=required
        --customize-hook="cat > \$1/etc/apt/sources.list.d/debian.sources <<EOF
Types: deb
URIs: http://deb.debian.org/debian
Suites: $DIST $DIST-updates $DIST-backports
Components: main contrib non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: http://security.debian.org/debian-security
Suites: $DIST-security
Components: main contrib non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF"
    )

elif ubuntu-distro-info --all | grep -qx "$DIST"; then
    mirror=http://archive.ubuntu.com/ubuntu
    [[ "$ARCH" == "i386" || "$ARCH" == "amd64" ]] || mirror=http://ports.ubuntu.com/ubuntu-ports

    suite=(
        --components=main
        --variant=required
        --customize-hook="cat > \$1/etc/apt/sources.list.d/ubuntu.sources <<EOF
Types: deb
URIs: $mirror
Suites: $DIST $DIST-updates $DIST-backports $DIST-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF"
    )
fi

cache=/var/cache/apt/archives
suite=(
    --architectures=$ARCH
    --setup-hook="mkdir -p \$1$cache"
    --setup-hook="mount --bind $cache \$1$cache"
    "${suite[@]}"
    --include=apt,ca-certificates,dbus,systemd
    --customize-hook="rm -rv \$1/etc/apt/sources.list \$1/etc/apt/trusted.gpg.d/"
    --customize-hook="chroot \$1 apt -y update"
    --customize-hook="chroot \$1 apt -y full-upgrade"
    --customize-hook="umount \$1$cache"
)

mmdebstrap -v "${suite[@]}" $DIST $cage $mirror
