#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"

bin=$(dirname "$0")/bin
cage=./cage
apt=$cage/etc/apt

export ARCH=${ARCH:-$(dpkg-architecture -q DEB_BUILD_ARCH)}
export DIST=${DIST:-resolute}

$bin/stop $cage
$bin/purge $cage
echo

$bin/bootstrap $cage
echo

$bin/spawn $cage
echo

cyan "Starting stage3"
cp -v $(dirname "$0")/deb/*.deb $cage/root/
cp -v $bin/stage3 $cage/root/
$bin/shell $cage /root/stage3 "$DIST" "$@"
echo

$bin/stop $cage
