#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"

bin=$(dirname "$0")/bin
cage=./cage
apt=$cage/etc/apt

export ARCH=${ARCH:-$(dpkg-architecture -q DEB_BUILD_ARCH)}
export DIST=${DIST:-resolute}

$bin/stop $cage
$bin/purge $cage
echo

$bin/bootstrap $cage
echo

if [[ "$DIST" == "unstable" || "$DIST" == "sid" ]]; then
    cyan "Updating Debian sources"
    rm -r $apt/{sources.list,trusted.gpg.d}
    cp -v apt/sources.list.d/debian-sid.sources $apt/sources.list.d/
    echo

elif [[ "$DIST" == "stable" ]] || debian-distro-info --all | grep -qx "$DIST"; then
    cyan "Updating Debian sources"
    rm -r $apt/{sources.list,trusted.gpg.d}
    cp -v apt/sources.list.d/debian.sources $apt/sources.list.d/
    sed -ri -e "s/%distro%/$DIST/g; s/%arch%/$ARCH/g" $apt/sources.list.d/debian.sources
    echo

elif ubuntu-distro-info --all | grep -qx "$DIST"; then
    cyan "Updating Ubuntu sources"
    rm -r $apt/{sources.list,trusted.gpg.d}
    cp -v apt/sources.list.d/ubuntu.sources $apt/sources.list.d/
    sed -ri -e "s/%distro%/$DIST/g; s/%arch%/$ARCH/g" $apt/sources.list.d/ubuntu.sources

    url=http://ports.ubuntu.com/ubuntu-ports
    [[ "$ARCH" == "i386" || "$ARCH" == "amd64" ]] || sed -ri -e "s|URIs: .*|URIs: $url|" $apt/sources.list.d/ubuntu.sources
    echo
fi

$bin/spawn $cage
echo

cyan "Starting stage3"
cp -v $(dirname "$0")/deb/*.deb $cage/root/
cp -v $bin/stage3 $cage/root/
$bin/shell $cage /root/stage3 "$DIST" "$@"
echo

$bin/stop $cage
