#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"

cage=${1:-cage}
name=$(basename "$cage")

rm -rv $cage/{root,home/*}/.bash_history 2>/dev/null

echo
cyan "Packaging $name"
alias tarx="tar --xattrs --xattrs-include='*' --acls --special"
tarx -cvzpf image.tar.gz -C $cage "$@" .
