#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"

cage=${1:-cage}
name=$(basename "$cage")

if [[ -d "$cage" ]]; then
    for n in 5 4 3 2 1; do
        red -ne "\rPurging $name in"; echo -n " $n ... "
        sleep 1
    done
    echo

    umount $cage/var/cache/apt/archives 2>/dev/null || true
    rm -rv $cage
fi
mkdir $cage
