#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"

cage=${1:-cage}
name=$(basename "$cage")

cyan "Spawning $name"
systemd-nspawn --bind=/var/cache/apt/archives --directory=$cage --machine=$name --resolv-conf=bind-stub --timezone=off "${@:2}"
