#!/bin/bash
set -e
shopt -s dotglob

cyan() { tput setaf 6; echo "$@"; tput sgr0; }

unset minimal no_kernel pika

for p in $@; do
    case $p in
        minimal)   minimal=1;;
        no-kernel) no_kernel=1;;
        pika)      pika=1;;
    esac
done

export DEBIAN_FRONTEND=noninteractive

cyan "Updating system"
apt -y update
echo
apt -y full-upgrade --no-install-recommends
apt-mark showmanual | xargs apt-mark auto
echo

install_package()
{
    local pkg=$1
    shift

    cyan "Installing $pkg"
    apt -y install --no-install-recommends $pkg $@
    echo

    if [[ ! "$minimal" ]]; then
        cyan "Installing $pkg+"
        rec=$(apt-cache show $pkg | sed -n "/Recommends:/ { s///; s/,//g; p }")
        man=$(apt-mark showmanual)

        rec=$(echo $man $man $rec | tr ' ' '\n' | sort | uniq -u)
        val=$(for p in $rec; do ((2 == $(apt-cache showpkg $p | grep -A3 "^Provides:" | wc -l))) || echo $p; done)
        new=$(apt-get -s install --no-install-recommends $val $@ | grep "^Inst " | cut -d' ' -f2)

        if [[ "$new" ]]; then
            apt -y install --no-install-recommends $new
            apt-mark auto $new
        fi
        echo
    fi
}

install_package cccp-standard-meta

cyan "Generating locales"
sed -ri -e "s/# (en_US.UTF-8.*)/\1/" /etc/locale.gen
echo LANG=en_US.UTF-8 > /etc/default/locale
dpkg-reconfigure -fnoninteractive locales
echo

cyan "Creating fstab"
cat > /etc/fstab <<EOF
# <source>      <target>        <type>  <options>                   <dump>  <pass>

LABEL=root      /               ext4    noatime,errors=remount-ro   0       1
LABEL=efi       /boot/efi       vfat    noatime,umask=0077          0       1

#/swapfile      none            swap    sw                          0       0
EOF

cyan "Setting hostname"
echo linux > /etc/hostname

cyan "Modifying journald.conf"
sed -ri -e "s/#(SplitMode)=.*/\1=none/" /etc/systemd/journald.conf

cyan "Modifying logind.conf"
sed -ri -e "
    s/#(NAutoVTs)=.*/\1=12/;
    s/#(ReserveVT)=.*/\1=1/;
    s/#(HandlePowerKey)=.*/\1=suspend/;
    s/#(HandlePowerKeyLongPress)=.*/\1=poweroff/;
    s/#(HandleLidSwitch(ExternalPower)?)=.*/\1=suspend/;
" /etc/systemd/logind.conf
systemctl disable getty@tty1.service

cyan "Forcing color terminal"
sed -ri -e "s/#(force_color_prompt)=.*/\1=yes/" /etc/skel/.bashrc

if [[ ! "$no_kernel" ]]; then
    install_package cccp-boot-meta

    cyan "Adding i915 to initramfs"
    echo "i915" >> /etc/initramfs/modules
fi

cyan "Adding support for .profile.d"
cat >> /etc/skel/.profile <<'EOF'

if [ -d "$HOME/.profile.d" ]; then
  for i in $(run-parts --list --regex '^[a-zA-Z0-9_][a-zA-Z0-9._-]*\.sh$' "$HOME/.profile.d"); do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
EOF

if [[ ! "$minimal" ]]; then
    install_package term-meta

    cyan "Setting console font"
    echo "FONT='courier64x32.psf'" >> /etc/default/console-setup

    install_package neovim-meta git-
fi

cyan "Updating root files"
cp -rv /etc/skel/* /root/
sed -ri -e "s/01;32m/01;31m/" /root/.bashrc
echo

cyan "Disabling services"
systemctl disable apt-daily-upgrade.timer apt-daily.timer dpkg-db-backup.timer man-db.timer motd-news.timer || true
echo

cyan "Cleaning up"
rm -rv /etc/{apparmor.d,cron.*,init.d,rc?.d,rsyslog.d} || true
