#!/bin/bash
set -e

PATH=$(dirname "$0")/bin:$PATH
source color

(($EUID)) && fail "Must be root"
(($#< 1)) && fail "Specify username to add"

cage=./cage
spawn $cage
cyan "Creating user $1"
shell $cage /usr/bin/homectl create --member-of=audio,render,sudo,systemd-journal,users,video "$@"
stop  $cage
