#!/bin/bash
set -e

cyan() { tput setaf 6; echo "$@"; tput sgr0; }
 red() { tput setaf 1; echo "$@"; tput sgr0; }
fail() { red "$@"; exit 1; }

(($EUID)) && fail "Must be root"
(($#< 1)) && fail "Specify username to add"

bin=$(dirname "$0")/bin
cage=./cage

$bin/spawn $cage
cyan "Creating user $1"
$bin/shell $cage /usr/bin/homectl create --member-of=audio,render,sudo,systemd-journal,users,video "$@"
$bin/stop  $cage
